server:
  port: 8082
spring:
  application:
    name: Manager-boot
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Hotel

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: Amma@2000
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true